### PR TITLE
Keytar

### PR DESCRIPTION
**Pull request by americk0**
Swaps out `clortho` dependency for `keytar` which supports Linux keychains as well as OSX and Windows. This also adds warnings about using plaintext files for credential storage when no keychain can be found, and provides a third authentication option in `alks-developer-configure` that will have the CLI skip saving a password so that you can be prompted for it each time

### CODE REVIEW

**Comment by amagana3** [comment]
I am testing now. Just want to confirm @americk0, I've never used the old CLI to save my password to keychain. Is it normal for this new keytar to constantly ask for your password every single command? That is what is happening today with `keytar`

**Review by amagana3 — DISMISSED** [review]
Verified it all on my end, locally. Works well and looks better than before! LGTM 👍🏼

**Comment by americk0** [comment]
That's odd. It shouldn't be prompting for your password every time you do things like generate keys with `alks sessions open` unless you haven't configured a password/token via `alks developer configure`, `alks developer login`, or `alks developer login2fa`. It defaults to asking every time until you configure it not to but once you configure it to store your password it shouldn't prompt you each time

**Review by amagana3 — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
